// ui/components/dashboard/GovernancePanel.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, ShieldAlert, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useI18n } from "@/hooks/useI18n";
import { getApiBaseUrl } from "@/lib/api-url";

type GovernanceCounts = {
  contradiction: number;
  semantic_duplicate: number;
  importance_reassessment: number;
  split_candidate: number;
  total: number;
};

type GovernanceMetrics = {
  applied_count: number;
  rejected_count: number;
  needs_review_count: number;
  review_queue_age_hours: number;
  rollback_rate: number;
  policy_version: string;
};

export function GovernancePanel() {
  const { messages: t } = useI18n();
  const [counts, setCounts] = useState<GovernanceCounts | null>(null);
  const [metrics, setMetrics] = useState<GovernanceMetrics | null>(null);

  useEffect(() => {
    let active = true;
    Promise.all([
      fetch(`${getApiBaseUrl()}/api/v1/governance/counts`).then((r) => r.json()),
      fetch(`${getApiBaseUrl()}/api/v1/governance/metrics`).then((r) => r.json()),
    ])
      .then(([cPayload, mPayload]) => {
        if (!active) return;
        const cData = (cPayload as { data?: GovernanceCounts }).data ?? (cPayload as GovernanceCounts);
        setCounts(cData ?? null);
        setMetrics(mPayload as GovernanceMetrics);
      })
      .catch(() => {
        if (active) {
          setCounts(null);
          setMetrics(null);
        }
      });
    return () => {
      active = false;
    };
  }, []);

  const actionable = counts?.total ?? 0;
  const applied = metrics?.applied_count ?? 0;
  const rejected = metrics?.rejected_count ?? 0;

  return (
    <Card className="border-zinc-800 bg-zinc-900/90 shadow-sm backdrop-blur-md">
      <CardHeader className="flex flex-row items-center justify-between space-y-0 border-b border-zinc-800/80 pb-3">
        <CardTitle className="flex items-center gap-2 text-sm font-semibold text-zinc-200">
          <ShieldAlert className="h-4 w-4 text-violet-400" />
          <span>记忆治理裁决中心 (Governance Cockpit)</span>
        </CardTitle>
        <div className="flex items-center gap-2">
          {actionable > 0 ? (
            <Badge variant="outline" className="border-amber-700/60 bg-amber-500/10 text-amber-300 text-xs">
              {actionable} 项待决策审阅
            </Badge>
          ) : (
            <Badge variant="outline" className="border-emerald-700/60 bg-emerald-500/10 text-emerald-300 text-xs">
              全量合规通过
            </Badge>
          )}
          <Link
            href="/governance"
            className="flex items-center gap-1 text-xs text-violet-400 hover:text-violet-300 transition-colors"
          >
            <span>完整治理台</span>
            <ArrowRight className="h-3 w-3" />
          </Link>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 pt-4">
        {actionable === 0 ? (
          <div className="flex items-center gap-3 rounded-lg border border-zinc-800 bg-zinc-950/60 p-4 text-xs">
            <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400" />
            <div className="space-y-0.5">
              <div className="font-semibold text-zinc-200">记忆流当前全量清洁</div>
              <p className="text-zinc-400">
                暂无冲突或冗余事实。LLM 治理与规则扫描器将持续监控新注入的事实，并在发现取代 (Supersedes) 或矛盾 (Contradicts) 时自动推送到待审流。
              </p>
            </div>
          </div>
        ) : (
          <div className="rounded-lg border border-amber-800/40 bg-amber-950/20 p-4 text-xs text-amber-200 space-y-1">
            <div className="font-semibold">检测到 {actionable} 条需要人工确认的高价值治理提案</div>
            <p className="text-zinc-400">
              请前往治理页面对冲突或重复事实进行裁决，或通过上方运维中心执行自动化归档。
            </p>
          </div>
        )}

        {/* 核心治理指标矩阵 */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 text-xs">
          <div className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-center">
            <div className="text-[11px] text-zinc-500">已批准执行</div>
            <div className="mt-1 text-xl font-bold text-emerald-400">{applied}</div>
          </div>
          <div className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-center">
            <div className="text-[11px] text-zinc-500">已忽略驳回</div>
            <div className="mt-1 text-xl font-bold text-rose-400">{rejected}</div>
          </div>
          <div className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-center">
            <div className="text-[11px] text-zinc-500">待决策积压</div>
            <div className="mt-1 text-xl font-bold text-amber-400">{actionable}</div>
          </div>
          <div className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-center">
            <div className="text-[11px] text-zinc-500">策略版本</div>
            <div className="mt-1 font-mono text-sm font-semibold text-zinc-200">
              {metrics?.policy_version || "v2.2"}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

// mcore-ui-vue/src/components/dashboard/GovernancePanel.vue
<template>
  <div class="mcore-card rounded-2xl overflow-hidden shadow-lg">
    <!-- 面板标题栏 -->
    <div class="flex items-center justify-between px-6 py-4 border-b border-zinc-800/80">
      <div class="flex items-center gap-2.5">
        <ShieldAlert class="h-4 w-4 text-violet-400" />
        <h2 class="text-sm font-semibold text-zinc-200">记忆治理裁决中心 (Governance Cockpit)</h2>
      </div>

      <div class="flex items-center gap-3">
        <span
          class="text-xs px-2.5 py-0.5 rounded-full font-medium border"
          :class="actionableCount > 0 ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300'"
        >
          {{ actionableCount > 0 ? `${actionableCount} 项待决策审阅` : '全量合规通过' }}
        </span>

        <router-link
          to="/governance"
          class="flex items-center gap-1 text-xs text-violet-400 hover:text-violet-300 font-medium transition-colors"
        >
          <span>完整治理台</span>
          <ArrowRight class="h-3 w-3" />
        </router-link>
      </div>
    </div>

    <div class="p-6 space-y-4">
      <!-- 上次自治理保洁提示条 -->
      <div class="flex items-center gap-2.5 rounded-xl border border-cyan-800/40 bg-cyan-950/20 p-3 text-xs text-cyan-200">
        <span class="text-sm">🧹</span>
        <div class="flex-1">
          <span class="font-semibold text-cyan-100">上次自治理保洁：</span>
          <span class="text-zinc-300 ml-1">
            活跃记忆 1,902 条 · 向量索引 100% 对齐 · 物理库强隔离就绪
          </span>
        </div>
      </div>

      <!-- 决策状态与分类大卡片 -->
      <div class="grid grid-cols-1 md:grid-cols-3 gap-3.5">
        <div class="bg-zinc-950/60 border border-zinc-800/80 rounded-xl p-4 flex flex-col justify-between">
          <div class="text-xs text-zinc-400 flex items-center justify-between">
            <span>矛盾事实冲突</span>
            <span class="text-xs text-amber-400 font-mono font-bold">{{ metrics.contradictions || 0 }}</span>
          </div>
          <div class="text-xs text-zinc-500 mt-2">新事实覆盖旧认知或待人工判定胜败方</div>
        </div>

        <div class="bg-zinc-950/60 border border-zinc-800/80 rounded-xl p-4 flex flex-col justify-between">
          <div class="text-xs text-zinc-400 flex items-center justify-between">
            <span>语义重复项</span>
            <span class="text-xs text-indigo-400 font-mono font-bold">{{ metrics.semantic_duplicates || 0 }}</span>
          </div>
          <div class="text-xs text-zinc-500 mt-2">高相似度多会话冗余提取，建议合并或沉淀</div>
        </div>

        <div class="bg-zinc-950/60 border border-zinc-800/80 rounded-xl p-4 flex flex-col justify-between">
          <div class="text-xs text-zinc-400 flex items-center justify-between">
            <span>已执行治理闭环</span>
            <span class="text-xs text-emerald-400 font-mono font-bold">{{ metrics.applied_decisions || 0 }}</span>
          </div>
          <div class="text-xs text-zinc-500 mt-2">自动与人工审批完成变更落地</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { ShieldAlert, ArrowRight } from 'lucide-vue-next';
import apiClient from '@/api/client';

const metrics = ref<any>({});

const actionableCount = computed(() => metrics.value.pending_reviews || 0);

async function fetchMetrics() {
  try {
    const res = await apiClient.get('/governance/metrics');
    metrics.value = res.data || {};
  } catch {}
}

onMounted(() => {
  fetchMetrics();
});
</script>
